# Generated by Django 5.0.7 on 2024-09-04 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='likedarticle',
            options={'verbose_name': 'Статьи с лайком', 'verbose_name_plural': 'Статьи с лайком'},
        ),
        migrations.CreateModel(
            name='FavoriteArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статьи добавленные в избранное',
                'verbose_name_plural': 'Статьи добавленные в избранное',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='favorites',
            field=models.ManyToManyField(related_name='favorite_article', through='main.FavoriteArticle', to=settings.AUTH_USER_MODEL),
        ),
    ]
