# Generated by Django 5.0.7 on 2024-07-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_article_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-time_create']},
        ),
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-time_create'], name='main_articl_time_cr_b86c53_idx'),
        ),
    ]
