# Generated by Django 5.0.7 on 2024-08-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_category_parent'),
    ]

    operations = [
    ]
