# Generated by Django 5.0.7 on 2024-08-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_article_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='parent',
        ),
    ]
