# Generated by Django 5.0.7 on 2024-08-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_article_category'),
        ('main', '0010_remove_category_parent'),
    ]

    operations = [
    ]
