# Generated by Django 5.0.7 on 2024-09-02 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_article_category'),
        ('main', '0011_merge_20240811_2030'),
    ]

    operations = [
    ]
